on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello world!"
      - name: Now it is
        run: |
          date
      - name: Directory content
        run: |
          ls -l
          
  # current_date_job:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Now it is
  #       run: |
  #         date

  #         # # Definition of jobs starts here

  # directory_content_job:
  #   runs-on: ubuntu-20.04
  #   steps:
  #     - name: Directory content
  #       run: |
  #         ls -l
