on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    # name: A job to say hello
    steps:
      - name: Say hello
        run: |
          echo "Hello world!"
