name: Testing stuff

on:
  push:
    branches:
      - master

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      - name: testing
        run: echo "${{ github.event.message.commits }}"

      - name: testing skip
        if: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}
        run: echo "found skip"

        # run: echo "found skip"
